server:
  port: 7777

# spring - mysql driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

    # ????? mapper.xml??? IoC????? ??? ? ?? ???? ??

mybatis:
  mapper-locations: mappers/**/*.xml
  # type-aliases-package: com.ohgiraffers.crud.MenuDTO # menuDto